name: Feature request
description: Suggest an idea for OmniWA-Agent
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thank you for contributing your ideas to make OmniWA-Agent better!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true
